baseURL = 'https://my-blog-ir75lgqwn-yaoximiaos-projects.vercel.app/'
languageCode = "zh-cn" 
title = "我的博客"
theme = "PaperMod" 

[params]
author = "Huggin"
description = "这个博客用于记录技术学习过程和生活"

# 菜单配置
[[menu.main]]
identifier = "posts"
name = "文章"
url = "/posts/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "标签"
url = "/tags/"
weight = 20